### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by alphatrix** [joshua-holmes/google-photos-metadata-fix#5]
I'm getting the following error when running the script:

```
PS N:\google-photos-metadata-fix> python run.py .\takeout-001\
Do you want to rename images if images have incorrect extensions?
If you consent, it will rename selected images, even if metadata cannot be applied later in the process.
e.g. a JPG file named "myimage.HEIC" would be renamed "myimage.jpg"
y,yes,n,no
n

Do you want to convert all HEIC images to JPG?
JPG is a more common file type than HEIC and will be viewable on almost any device.
y,yes,n,no
n

Applying metadata...
Traceback (most recent call last):
  File "N:\google-photos-metadata-fix\run.py", line 82, in <module>
    main()
  File "N:\google-photos-metadata-fix\run.py", line 77, in main
    imgs_modified = lib.process_files_in_dir(path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\google-photos-metadata-fix\src\lib.py", line 95, in process_files_in_dir
    for dirname in progressbar(file_pairs, redirect_stdout=True):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

**Comment by alphatrix** [comment]
ChatGPT said to install progressbar2, that fixed it for me.
